spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # Connection Pool 설정 추가
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
    show-sql: true

  #  redis:
  #    host: localhost
  #    port: 6379

  config:
    activate:
      on-profile: local
    import:
      application-secret.yml

jwt:
  secret: ${JWT_SECRET}






