server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
        show-sql: true

    # Initial Data config
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  redis:
  #    host: localhost
  #    port: 6379

  config:
    activate:
      on-profile: local
    import:
      application-secret.yml

jwt:
  secret: ${JWT_SECRET}

sentiment:
  clientId: ${NAVER_CLIENT_ID}
  clientSecret: ${NAVER_CLIENT_SECRET}

chatgpt:
  key: ${GPT_SECRET}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
